---
# tasks file for auditd
# - name: Install requirements
#   ansible.builtin.package:
#     name: bash
#     state: present

- name: Install audit
  ansible.builtin.package:
    name: "{{ auditd_package_name }}"
    state: present

- name: Configure auditd
  ansible.builtin.copy:
    src: "{{ auditd_config_file }}"
    dest: "{{ auditd_config_directory }}/{{ auditd_config_file }}"
    mode: "0640"
  notify:
    - Restart auditd
  when:
    - auditd_manage_config

- name: Create rules.d directory
  ansible.builtin.file:
    path: "{{ auditd_config_directory }}/rules.d"
    state: directory
    mode: "0750"

- name: Place custom.rules
  ansible.builtin.template:
    src: custom.rules.j2
    dest: "{{ auditd_config_directory }}/rules.d/custom.rules"
    mode: "0664"
  notify:
    - Run augenrules
  when:
    - auditd_manage_rules

- name: Start and enable auditd
  ansible.builtin.service:
    name: "{{ auditd_service }}"
    state: started
    enabled: true
  when:
    - auditd_start_service
